# SPDX-FileCopyrightText: 2021 Aaron Dewes
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Wallets
  name: LnMe
  version: 1.4.0
  tagline: Receive tips over Lightning
  description: >-
    This app allows you to receive tips over Lightning.

    You can share the onion address of this app with others and they can dynamically generate an invoice using this app.

    Using some apps, like BlueWallet, users can directly send tips to our Lightning address.

    Your lightning address is <your-name-or-anything-you-like-it-doesn't-matter>@<the-onion-url-of-this-app>.onion.

    Please note: This app only works on Citadel 0.5.1 and above (Yes, that update doesn't exist yet).

    The Lightning Address feature will only work with the next BlueWallet release.
  developer: Michael Bumann
  website: https://ln.michaelbumann.com/
  dependencies:
  - lnd
  repo: https://github.com/bumi/lnme
  support: https://github.com/bumi/lnme/issues
  gallery:
    - https://raw.githubusercontent.com/bumi/lnme/master/lnme-demo.gif
containers:
- image: ghcr.io/runcitadel/lnme:master
  user: 1000:1000
  environment:
    LNME_LND_ADDRESS: $LND_IP:$LND_GRPC_PORT
    LNME_LND_CERT_PATH: /lnd/tls.cert
    LNME_LND_MACAROON_PATH: /lnd/data/chain/bitcoin/$BITCOIN_NETWORK/invoice.macaroon
  name: web
  port: 1323
  permissions:
  - lnd
