# SPDX-FileCopyrightText: 2021 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Development
  name: code-server
  version: 3.12.0
  tagline: Run VS Code on your Citadel
  description: >-
    This app doesn't  have a description yet.
  developer: Coder
  website: https://coder.com
  dependencies: []
  repo: https://github.com/cdr/code-server
  support: https://github.com/cdr/code-server/discussions
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED

containers:
- name: server
  image: codercom/code-server:3.12.0@sha256:44415390c118663dd58119ea4d3891ed32f1f56181144af671cf9c0de41d6132
  user: 1000:1000
  environment:
    PASSWORD: $APP_SEED
  data:
  - data:/home/coder
