# SPDX-FileCopyrightText: Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Lightning Node Management
  name: Ride The Lightning
  version: 0.11.2
  tagline: Manage lightning node operations better
  description: >-
    Haven't written a desription yet for this, sorry.
  developer: Shahana and Suheb
  website: https://github.com/Ride-The-Lightning/RTL
  dependencies:
  - lnd
  - bitcoind
  repo: https://github.com/Ride-The-Lightning/RTL
  support: https://twitter.com/RTL_App
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: moneyprintergobrrr
  mainContainer: web

containers:
- image: shahanafarooqui/rtl:0.11.2@sha256:225b47abcca053e3ea831431742a08b3f3e70b12654df6fd703f617ad965f34e
  user: 1000:1000
  port: 3000
  environment:
    PORT: 3000
    RTL_CONFIG_PATH: /data
    CHANNEL_BACKUP_PATH: /data/backup
    LN_IMPLEMENTATION: LND
    LN_SERVER_URL: https://$LND_IP:$LND_REST_PORT
    MACAROON_PATH: /lnd/data/chain/bitcoin/$BITCOIN_NETWORK
    CONFIG_PATH: /lnd/lnd.conf
    SWAP_SERVER_URL: https://$APP_RIDE_THE_LIGHTNING_LOOP_IP:8081
    SWAP_MACAROON_PATH: /loop/.loop/$BITCOIN_NETWORK
    BOLTZ_SERVER_URL: "https://$APP_RIDE_THE_LIGHTNING_BOLTZ_IP:9003"
    BOLTZ_MACAROON_PATH: "/boltz/.boltz-lnd/macaroons"
  name: web
  data:
  - loop:/loop
  - boltz:/boltz
  - rtl:/data
  permissions:
  - lnd
  - bitcoind

- name: loop
  image: ghcr.io/runcitadel/loop:v0.16.0-beta@sha256:ee441e73079012f5b8777c744f26fb3fb4b0f5b9485395ab5ca9da80e60fc704
  user: 1000:1000
  environment:
    HOME: /data
  command:
  - --network=$BITCOIN_NETWORK
  - --lnd.host="$LND_IP:$LND_GRPC_PORT"
  - --lnd.macaroonpath="/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon"
  - --lnd.tlspath="/lnd/tls.cert"
  - --restlisten=0.0.0.0:8081
  data:
  - loop:/data
  permissions:
  - lnd

- name: boltz
  image: boltz/boltz-lnd:1.2.6@sha256:01a56dd357a2460bfd0ecdd726d6db3ab59d78ee691250831d09ba5de3fec7ce
  user: "1000:1000"
  restart: "on-failure"
  environment:
    HOME: "/data"
  data:
  - boltz:/data
  command:
    - --lnd.host="$LND_IP"
    - --lnd.macaroon="/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon"
    - --lnd.certificate="/lnd/tls.cert"
    - --rpc.rest.host="$APP_RIDE_THE_LIGHTNING_BOLTZ_IP"
    - --rpc.rest.port="9003"
  permissions:
  - lnd
